In [1]:
import numpy as np
import pandas as pd

In [2]:
## Loading Dataset

df = pd.read_csv("students_placement.csv")

In [3]:
df.shape

(300, 4)

In [4]:
df.sample(5)

,cgpa,iq,profile_score,placed
154,5.56,117,68,1
229,9.30,85,68,1
120,7.93,95,50,1
203,8.47,87,72,1
106,5.61,108,74,0


In [5]:
## Feaure -Label Split

X = df.drop("placed",axis = 1)
y = df["placed"]

In [6]:
## Train - test split

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [7]:
## Feature Scaling

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [8]:
from sklearn.metrics import accuracy_score,confusion_matrix,f1_score

In [9]:
## Model- 1 : Logistic Regression

from sklearn.linear_model import LogisticRegression
logit = LogisticRegression()
logit.fit(X_train_scaled,y_train)
y_pred = logit.predict(X_test_scaled)
print(accuracy_score(y_test,y_pred))
print(f1_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.85
0.8524590163934426
[[25  4]
 [ 5 26]]


In [10]:
## Model -2 : Random Forest

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train_scaled,y_train)
y_pred_rf = rf.predict(X_test_scaled)
print(accuracy_score(y_test,y_pred_rf))
print(f1_score(y_test,y_pred_rf))
print(confusion_matrix(y_test,y_pred_rf))


0.85
0.8571428571428571
[[24  5]
 [ 4 27]]


In [11]:
## Model - 3 : Support Vector Machine

from sklearn.svm import SVC
svm = SVC(kernel = "rbf")
svm.fit(X_train_scaled,y_train)
y_pred_svm = svm.predict(X_test_scaled)
print(accuracy_score(y_test,y_pred_svm))
print(f1_score(y_test,y_pred_svm))
print(confusion_matrix(y_test,y_pred_svm))


0.85
0.8524590163934426
[[25  4]
 [ 5 26]]


In [12]:
## Model - 4 :  K- Nearest Neighbour

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train_scaled,y_train)
y_pred_knn = knn.predict(X_test_scaled)
print(accuracy_score(y_test,y_pred_knn))
print(f1_score(y_test,y_pred_knn))
print(confusion_matrix(y_test,y_pred_knn))


0.8666666666666667
0.875
[[24  5]
 [ 3 28]]


In [13]:
## Model - 5 : Naive Bayes

from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train_scaled,y_train)
y_pred_nb = nb.predict(X_test_scaled)
print(accuracy_score(y_test,y_pred_nb))
print(f1_score(y_test,y_pred_nb))
print(confusion_matrix(y_test,y_pred_nb))

0.8333333333333334
0.8387096774193549
[[24  5]
 [ 5 26]]


In [14]:
## Creating the Pipeline for scaling+prediction using K-NN

from sklearn.pipeline import Pipeline
pipeline = Pipeline([("scaler",StandardScaler()),("knn",KNeighborsClassifier())])
pipeline.fit(X_train,y_train)
y_pred_pipeline = pipeline.predict(X_test)
print(accuracy_score(y_test,y_pred_pipeline))
print(f1_score(y_test,y_pred_pipeline))
print(confusion_matrix(y_test,y_pred_pipeline))

0.8666666666666667
0.875
[[24  5]
 [ 3 28]]


In [15]:
## Saving the pipeline model

import joblib
joblib.dump(pipeline,"student_placement_pipeline_model.pkl")


['student_placement_pipeline_model.pkl']